# Generated by Django 5.2.4 on 2025-08-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_ticket_is_scanned_ticket_scanned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file to accompany the news article', null=True, upload_to='news_videos/'),
        ),
    ]
