# Generated by Django 5.2.4 on 2025-08-03 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_news_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='attendance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='corners_away',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='corners_home',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='fouls_away',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='fouls_home',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='highlights',
            field=models.TextField(blank=True, help_text='Key moments and highlights'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_summary',
            field=models.TextField(blank=True, help_text='Auto-generated match summary'),
        ),
        migrations.AddField(
            model_name='match',
            name='possession_away',
            field=models.PositiveIntegerField(blank=True, help_text='Away team possession percentage', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='possession_home',
            field=models.PositiveIntegerField(blank=True, help_text='Home team possession percentage', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red_cards_away',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red_cards_home',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='shots_away',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='shots_home',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='shots_on_target_away',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='shots_on_target_home',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='weather',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='yellow_cards_away',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='yellow_cards_home',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('substitution', 'Substitution'), ('foul', 'Foul'), ('corner', 'Corner'), ('free_kick', 'Free Kick'), ('penalty', 'Penalty'), ('injury', 'Injury'), ('other', 'Other')], max_length=20)),
                ('minute', models.PositiveIntegerField(help_text='Minute of the event')),
                ('team', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('additional_info', models.CharField(blank=True, help_text='Additional details like assist, card reason, etc.', max_length=200)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ticketing.match')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
    ]
