# Generated by Django 5.2.4 on 2025-08-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_match_attendance_match_away_score_match_corners_away_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.CharField(default='Bo Rangers FC', help_text='Home team name', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_logo',
            field=models.ImageField(blank=True, help_text='Home team logo', null=True, upload_to='team_logos/'),
        ),
    ]
