# Generated by Django 5.2.4 on 2025-08-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_match_home_team_match_home_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='opponent_logo',
            field=models.ImageField(blank=True, help_text='Opponent team logo', null=True, upload_to='team_logos/'),
        ),
    ]
